name: "Scan IP ranges"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

env:
  # List of filenames of IP ranges to scan
  FILENAMES: [aws.json, google.json, google_v2.json]

jobs:
  scan_ips:
    runs-on: ubuntu-latest
    needs: scrape_ips
    steps:
      - uses: actions/checkout@v3
      - name: Scan IP ranges
        run: |
          for file in ${{ env.FILENAMES }}
          do
            while read -r line
            do
              nmap -oX "results/${{ env.GITHUB_RUN_ID }}-${file%.*}-${line//\//-}.xml" -v -sV -T4 ${line}
            done < "ip_ranges/$file"
          done
      - name: Commit results
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add results/${{ env.GITHUB_RUN_ID }}-*
          timestamp=$(date -u)
          git commit -m "Updated scan results at ${timestamp}"
