name: Nmap Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
    
jobs:
  nmap-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: [aws]
        include:
        - source: aws
          url: "https://ip-ranges.amazonaws.com/ip-ranges.json"
        -source: Google
          "https://www.gstatic.com/ipranges/goog.json"
        -source: Google v2
          "https://www.gstatic.com/ipranges/cloud.json"
        -source: Oracle
          "https://docs.oracle.com/en-us/iaas/tools/public_ip_ranges.json"
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Nmap
      uses: docker://nmap/nmap:latest

    - name: Download and process JSON
      run: |
        mkdir -p ip_ranges
        curl ${{ matrix.url }} | jq "[.prefixes[] | .ip_prefix]" > ip_ranges/${{matrix.source}}.json

    - name: Scan IP Ranges with Nmap
      run: |
        cat ip_ranges/${{matrix.source}}.json | while read -r ip_range; do
          docker run --rm -v $(pwd):/tmp nmap/nmap:latest nmap -oX - -p 22,80,443 $ip_range > nmap-scan-$ip_range.xml
        done

    - name: Convert Nmap Output to JSON
      run: |
        for file in $(ls nmap-scan-*.xml); do
          nmap2json $file > ${file%.xml}.json
        done

    - name: Commit and Push Results
      uses: actions/upload-artifact@v2
      with:
        name: nmap-scans.zip
        path: nmap-scan-*.json
        archive: true
