name: Scan IPs

on:
  schedule:
    # Scan IPs once a week
    - cron: "0 0 * * 0"

env:
  # Define the list of JSON URLs
  JSON_URLS: |
    https://ip-ranges.amazonaws.com/ip-ranges.json
    https://www.gstatic.com/ipranges/goog.json
    https://www.gstatic.com/ipranges/cloud.json
    https://endpoints.office.com/endpoints/worldwide?clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7
    https://docs.oracle.com/en-us/iaas/tools/public_ip_ranges.json
    https://api.github.com/meta
    https://geoip.linode.com/
    https://raw.githubusercontent.com/lord-alfred/ipranges/main/amazon/ipv4.txt

jobs:
  scan_ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch JSON data
      id: fetch_json
      run: |
        for url in $(echo "$JSON_URLS" | tr '\n' ' '); do
          curl -sSL $url | jq -r '.prefixes[].ip_prefix' >> ip_prefixes.txt
        done

    - name: Scan IPs
      uses: actions/nmap@v1
      with:
        args: -iL ip_prefixes.txt

    - name: Upload scan results
      uses: actions/upload-artifact@v2
      with:
        name: scan_results
        path: ip_prefixes.txt
