name: "Scrape and Scan IP ranges"

on:
  workflow_dispatch:
  schedule:
    # Scrape and scan IPs once a week
    - cron: "0 0 * * 0"

jobs:
  scrape_ips:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: [aws, Google, Google v2, Oracle]
        include:
          - source: aws
            url: "https://ip-ranges.amazonaws.com/ip-ranges.json"
          - source: Google
            url: "https://www.gstatic.com/ipranges/goog.json"
          - source: Google v2
            url: "https://www.gstatic.com/ipranges/cloud.json"
    steps:
      - uses: actions/checkout@v3
      - name: Download and process JSON
        run: |
          mkdir -p ip_ranges
          curl ${{ matrix.url }} | jq "[.prefixes[] | .ip_prefix]" > ip_ranges/${{matrix.source}}.json
      - name: Scan IPs with nmap
        run: |
          nmap -iL ip_ranges/${{matrix.source}}.json -oX scan_results/${{matrix.source}}_scan.xml -v -A
      - name: Commit JSON and scan results
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add ip_ranges/${{matrix.source}}.json scan_results/${{matrix.source}}_scan.xml
          timestamp=$(date -u)
          git commit -m "Updated IP range source "${{matrix.source}}" and scan results at ${timestamp}"
